[build-system]
requires = ["setuptools>=68", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "ohlcv-pipeline"
version = "0.3.0"
description = "OHLCV pipeline: C1 (DataLayer), C2 (DataQuality), C3 (Features.Core)"
readme = "README.md"
authors = [ { name = "Project" } ]
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
  "numpy>=1.26",
  "pandas>=2.2",
  "pyarrow>=15",
  "requests>=2.31",
  "filelock>=3.12",
  "pyyaml>=6",
]

[project.optional-dependencies]
dev = [
  "pytest>=7",
  "pytest-cov>=4",
  "ruff>=0.5",
  "black>=24",
  "isort>=5",
  "mypy>=1.8",
  "numba>=0.59",
  # type stubs
  "pandas-stubs>=2",
  "types-requests",
  "types-PyYAML",
]

[project.scripts]
# существующий CLI C1
c1-ohlcv = "ohlcv.cli:main"
# новый CLI C3
features-core = "ohlcv.features.cli:main"

[tool.pytest.ini_options]
addopts = "-q"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 100

[tool.mypy]
python_version = "3.11"
strict = true
packages = ["ohlcv"]

[[tool.mypy.overrides]]
module = [
  "pandas",
  "pandas.*",
  "requests",
  "yaml",
  "pyarrow",
  "pyarrow.*",
]
ignore_missing_imports = true

# CLI-модули допускаем без полной аннотации, чтобы не блокировать сборку
[[tool.mypy.overrides]]
module = [
  "ohlcv.cli",
  "ohlcv.features.cli",
]
disallow_untyped_defs = false
check_untyped_defs = false
warn_return_any = false
