[project]
name = "c1-ohlcv"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "pandas>=2.2",
  "pyarrow>=15",
  "requests>=2.31",
  "python-dateutil>=2.9",
  "pytz>=2024.1",
  "tenacity>=8.2",
  "filelock>=3.13",
  "pyyaml>=6.0",
]
