api:
  adapter: bybit
  base_url: https://api.bybit.com
  read_only_key_ref: secret://bybit/dev/read_key
  timeout_s: 10
  max_retries: 5
  max_concurrent: 2
  page_size: 1000

storage:
  base_dir: /data
  compression: zstd
  zstd_level: 7
  row_group_size: 256000
  tail_days: 14

resample:
  tfs: [5m, 15m, 1h]
  strict_gaps: true  # is_gap=true при недоборе минут/дырках; синтетика для пустых окон

quality:
  max_gap_pct: 0.0001       # верхняя доля пропусков по отчёту C1
  gap_recovery_days: 7      # горизонт восстановления для дозагрузок
  sanity_check_samples: 200 # выборка для ручной верификации

logging:
  level: INFO
