api:
  adapter: bybit
  base_url: https://api.bybit.com
  read_only_key_ref: secret://bybit/dev/read_key
  timeout_s: 10
  max_retries: 5
  max_concurrent: 2
  page_size: 1000

storage:
  base_dir: /data
  compression: zstd
  zstd_level: 7
  row_group_size: 256000
  tail_days: 14

logging:
  level: INFO
