# Пример конфига для построения признаков C3
# Соответствует полям FeatureConfig из ohlcv.features.core
# Скопируйте как features.yaml и при необходимости измените окна.

# Окна для реализованной волатильности (std лог-ретёрнов)
rv: [30, 60, 120, 180]

# Окна EMA по close
ema: [5, 10, 20, 50]

# Окна моментума (c - c.shift(k))
mom: [1, 5, 10]

# Окна Donchian для ширины коридора
donch: [20, 55]

# Окна Z-score по close
z: [60, 120]

# Метка версии сборки признаков
build_version: "C3-Features-1.2"
