# C3 Features configuration
# Ключи соответствуют FeatureConfig из ohlcv.features.core

rv: [30, 60, 120, 180]        # окна для реализованной волатильности (std лог-ретёрнов)
ema: [5, 10, 20, 50]           # окна EMA по close
mom: [1, 5, 10]                # окна моментума (c - c.shift(k))
donch: [20, 55]                # окна Donchian для ширины коридора
z: [60, 120]                   # окна Z-score по close

build_version: "C3-Features-1.2"
