# Конфиг C3 Features — пример. Все поля опциональны, отсутствующие берут значения по умолчанию.
rv_windows: [20, 60]          # rolling std(logret, n), ddof=1
z_windows: [20, 96]            # окна для z-score (close/range/volume/ATR)
ema_windows: [20, 50]          # EMA по close
sma_windows: [20, 50]          # SMA по close
mom_windows: [20, 50, 100]     # моментумы по close

# Каналы волатильности и тренда
atr_window: 14                 # ATR (Wilder)
adx_window: 14                 # ADX/DI (Wilder)
rsi_window: 14                 # RSI

# Каналы диапазона и ликвидности
donch_windows: [20, 55]        # Donchian HH/LL/width (+ *_pct и break_dir)
vwap_roll_window: 96           # скользящий VWAP (кол-во баров)
updownvol_window: 20           # окна для upvol/downvol/vol_balance

# Поведение
strict: false                  # строгая валидация входа (NaN/инварианты → ошибка)
build_version: null            # явная версия сборки; если null — вычисляется автоматически