name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install lint tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.8 black==24.8.0 isort==5.13.2 mypy==1.8

      - name: Ruff lint
        run: ruff check .

      - name: Black check
        run: black --check .

      - name: isort check
        run: isort --check-only .

      - name: mypy
        run: mypy ohlcv

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install package (editable) with dev extras
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=ohlcv --cov-report=term-missing
